### ISSUE TITLE
Scratch followers not updating

### ISSUE THREAD

**Issue by Wjplatformer** [devxan/devxan#2]
# Oh man Xan!
---
### - Although it is not your fault, a possible solution (from a person who does not specialize in javascript and markdown), is to manually type it down :P
<br>
<br>
<br>
Also, just wanted to say Hi from scratch.

**Comment by devxan** [comment]
Hey, @Wjplatformer! Thanks for the report. Yeah, I noticed that too, but I don't know where else to get an auto-update follower count. 
hi! :D

**Comment by devxan** [comment]
@Wjplatformer Xancan has been banned and @Canxan has been banned then deleted. I switched the badges showing Xancan message count and followers to -Xanimation-'s. If you want, you can follow them 😅

**Comment by Wjplatformer** [comment]
### Although the scratch count is indeed bugged out, It is still similar in followers to your -Xanimation- account on scratch.
I will check out your Youtube! Did not see that earlier on! :grin:

**Comment by devxan** [comment]
I just added that! I might add more too.
