### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by Wjplatformer** [devxan/devxan#3]
# DB not working?
Scratch followers not working! Did it crash or under maintenance. Hope this gets resolved soon 🙏🏻

**Comment by devxan** [comment]
It's okay 🤷‍♂️

**Comment by Wjplatformer** [comment]
yeah...

**Comment by Wjplatformer** [comment]
At the point of writing it wasn't. Probably a regular thing?

**Comment by Wjplatformer** [comment]
Anyways, I realized that I am very vague. So what happened was the badge became a link, just like when I tried adding my own sources in, that it cannot be turned into messages for the badge. Clicking on the link directs you to whatever link you put.

**Comment by devxan** [comment]
If that happens, you can right-click on the text/broken image symbol and if the option to "Load Image" is there, choose that.

**Comment by Wjplatformer** [comment]
yeah, it works. Thanks :)
